---
root: true

env:
  browser: true
  es6: true

parser: babel-eslint

extends:
  - airbnb

rules:
  arrow-parens:
    - error
    - always
  comma-dangle:
    - error
    -
      arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
  max-len: off
  no-console: off
